version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Phishing Attempts Management Server
  server:
    build:
      context: ./phishing-attempts-management-server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - JWT_SECRET=cymulate
      - PORT=3000
      - NODE_ENV=development
      - DB_USER=avishaidotan
      - DB_USER_PASSWORD=2P7dKjFyW2JruDMn
      - DB_NAME=cymulate
      - FRONTEND_URL=http://localhost:5000
    restart: unless-stopped

  # Phishing Simulation Server
  phishing-server:
    build:
      context: ./phishing-simulation-server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=development
      - DB_USER=avishaidotan
      - DB_USER_PASSWORD=2P7dKjFyW2JruDMn
      - DB_NAME=cymulate
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=avishaidotan@gmail.com
      - SMTP_PASS=ughw agba ghcj nmhs
      - SMTP_FROM=avishaidotan@gmail.com
    restart: unless-stopped

networks:
  app-network:
    driver: bridge