# Docker Compose for Cymulate Application

# MongoDB credentials configuration
x-mongodb-credentials: &mongodb-credentials
  MONGO_INITDB_ROOT_USERNAME: your_mongodb_username
  MONGO_INITDB_ROOT_PASSWORD: your_mongodb_password
  MONGO_PORT: 27017
  MONGO_DB_NAME: your_database_name

# Base environment variables for all services
x-app-base-env: &app-base-env
  NODE_ENV: production
  MONGODB_URI: mongodb://your_mongodb_username:your_mongodb_password@mongodb:27017/your_database_name?authSource=admin
  # Service-to-service communication URLs
  SIMULATION_SERVER_URL: http://phishing-server:7000
  MANAGEMENT_SERVER_URL: http://phishing-management-app:3000

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      <<: *mongodb-credentials
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  phishing-management-app:
    build:
      context: .
      dockerfile: main-server.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./phishing-attempts-management-server/.env
    environment:
      <<: *app-base-env
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongodb
      - phishing-server

  phishing-server:
    build:
      context: ./phishing-simulation-server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - ./phishing-simulation-server/.env
    environment:
      <<: *app-base-env
      PORT: 7000
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - mongodb

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
