version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avishaidotan
      - MONGO_INITDB_ROOT_PASSWORD=2P7dKjFyW2JruDMn
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  # Phishing Attempts Management Server
  server:
    build:
      context: ./phishing-attempts-management-server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - JWT_SECRET=cymulate
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://avishaidotan:2P7dKjFyW2JruDMn@mongodb:27017/cymulate?authSource=admin
      - FRONTEND_URL=http://localhost:5000
    networks:
      - app-network
    restart: unless-stopped

  # Phishing Simulation Server
  phishing-server:
    build:
      context: ./phishing-simulation-server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://avishaidotan:2P7dKjFyW2JruDMn@mongodb:27017/cymulate?authSource=admin
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=avishaidotan@gmail.com
      - SMTP_PASS=ughw agba ghcj nmhs
      - SMTP_FROM=avishaidotan@gmail.com
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: